---------------------------------Trigger---------------------------
--create a table to store value
create table auditable(sno number generated by default as identity primary key,tablename varchar2(30),TransacName varchar2(30),username varchar2(30),trandate date);
select * from auditable;
----------------------------------
--updating or deleting employee
select * from employee;
update employee set salary=444 where eno= 2;
update employee set salary=544 where eno= 6;
update employee set salary=464 where eno= 7;
delete from employee where eno=2;







--trigger
create or replace trigger audittrigger after update or delete on employee for each row
declare
tran varchar2(30);
begin
tran:=case
when updating then 'update'
when deleting then 'delete'
end;
insert into auditable(tablename,TransacName ,username,transacdate) values('employee',tran,user,sysdate);
end;